# Generated by Django 5.1.3 on 2024-11-18 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Admin', 'Admin')], default='Student', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_description', models.TextField()),
                ('event_location', models.CharField(max_length=255)),
                ('event_time', models.DateTimeField()),
                ('event_created_at', models.DateTimeField(auto_now_add=True)),
                ('event_published_by', models.ForeignKey(db_column='event_published_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbapp.user')),
            ],
        ),
    ]
