# Generated by Django 4.2.16 on 2024-11-20 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Admin', 'Admin')], default='Student', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.CharField(choices=[('Khoury', 'Khoury'), ('COE', 'COE')], default='Khoury', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('event_description', models.TextField()),
                ('event_location', models.CharField(max_length=255)),
                ('event_time', models.DateTimeField()),
                ('event_created_at', models.DateTimeField(auto_now_add=True)),
                ('event_status', models.CharField(default='In process', max_length=50)),
                ('event_published_by', models.ForeignKey(db_column='event_published_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbapp.user')),
            ],
        ),
    ]
